const SET_USER = "SET_USER";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SIGNUP = "SIGNUP";
const RESET_PASSWORD = "RESET_PASSWORD";

export { SET_USER, LOGIN, SIGNUP, LOGOUT, RESET_PASSWORD };
